package com.eaie.dbmanage;

import java.util.HashSet;
import java.util.Set;


/**
 * Bigclass generated by MyEclipse - Hibernate Tools
 */

public class Bigclass  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String bigclass;
     private Integer bigclassid;
     private Set smallclasses = new HashSet(0);


    // Constructors

    /** default constructor */
    public Bigclass() {
    }

    
    /** full constructor */
    public Bigclass(String bigclass, Integer bigclassid, Set smallclasses) {
        this.bigclass = bigclass;
        this.bigclassid = bigclassid;
        this.smallclasses = smallclasses;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBigclass() {
        return this.bigclass;
    }
    
    public void setBigclass(String bigclass) {
        this.bigclass = bigclass;
    }

    public Integer getBigclassid() {
        return this.bigclassid;
    }
    
    public void setBigclassid(Integer bigclassid) {
        this.bigclassid = bigclassid;
    }

    public Set getSmallclasses() {
        return this.smallclasses;
    }
    
    public void setSmallclasses(Set smallclasses) {
        this.smallclasses = smallclasses;
    }
   








}