package com.eaie.dbmanage;

import java.util.Date;


/**
 * Classroom generated by MyEclipse - Hibernate Tools
 */

public class Classroom  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String subject;
     private String unit;
     private String takedate;
     private String starttime;
     private String endtime;
     private String classroom;
     private String director;
     private String tel;
     private Byte isagree;
     private Date pubtime;
     private String teacher;
     private Date replytime;


    // Constructors

    /** default constructor */
    public Classroom() {
    }

    
    /** full constructor */
    public Classroom(String subject, String unit, String takedate, String starttime, String endtime, String classroom, String director, String tel, Byte isagree, Date pubtime, String teacher, Date replytime) {
        this.subject = subject;
        this.unit = unit;
        this.takedate = takedate;
        this.starttime = starttime;
        this.endtime = endtime;
        this.classroom = classroom;
        this.director = director;
        this.tel = tel;
        this.isagree = isagree;
        this.pubtime = pubtime;
        this.teacher = teacher;
        this.replytime = replytime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getTakedate() {
        return this.takedate;
    }
    
    public void setTakedate(String takedate) {
        this.takedate = takedate;
    }

    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public String getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    public String getClassroom() {
        return this.classroom;
    }
    
    public void setClassroom(String classroom) {
        this.classroom = classroom;
    }

    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public Byte getIsagree() {
        return this.isagree;
    }
    
    public void setIsagree(Byte isagree) {
        this.isagree = isagree;
    }

    public Date getPubtime() {
        return this.pubtime;
    }
    
    public void setPubtime(Date pubtime) {
        this.pubtime = pubtime;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public Date getReplytime() {
        return this.replytime;
    }
    
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }
   








}