package com.eaie.dbmanage;



/**
 * Classname generated by MyEclipse - Hibernate Tools
 */

public class Classname  implements java.io.Serializable {


    // Fields    

     private ClassnameId id;


    // Constructors

    /** default constructor */
    public Classname() {
    }

    

   
    // Property accessors

    public ClassnameId getId() {
        return this.id;
    }
    
    public void setId(ClassnameId id) {
        this.id = id;
    }
   








}