package com.eaie.dbmanage;



/**
 * ClassnameId generated by MyEclipse - Hibernate Tools
 */

public class ClassnameId  implements java.io.Serializable {


    // Fields    

     private String bigclass;
     private String smallclass;


    // Constructors

    /** default constructor */
    public ClassnameId() {
    }

    
    /** full constructor */
    public ClassnameId(String bigclass, String smallclass) {
        this.bigclass = bigclass;
        this.smallclass = smallclass;
    }

   
    // Property accessors

    public String getBigclass() {
        return this.bigclass;
    }
    
    public void setBigclass(String bigclass) {
        this.bigclass = bigclass;
    }

    public String getSmallclass() {
        return this.smallclass;
    }
    
    public void setSmallclass(String smallclass) {
        this.smallclass = smallclass;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClassnameId) ) return false;
		 ClassnameId castOther = ( ClassnameId ) other; 
         
		 return ( (this.getBigclass()==castOther.getBigclass()) || ( this.getBigclass()!=null && castOther.getBigclass()!=null && this.getBigclass().equals(castOther.getBigclass()) ) )
 && ( (this.getSmallclass()==castOther.getSmallclass()) || ( this.getSmallclass()!=null && castOther.getSmallclass()!=null && this.getSmallclass().equals(castOther.getSmallclass()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBigclass() == null ? 0 : this.getBigclass().hashCode() );
         result = 37 * result + ( getSmallclass() == null ? 0 : this.getSmallclass().hashCode() );
         return result;
   }   





}