package com.eaie.dbmanage;

import java.util.Date;


/**
 * Commiepub generated by MyEclipse - Hibernate Tools
 */

public class Commiepub  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String branch;
     private String publist;
     private Date pubtime;


    // Constructors

    /** default constructor */
    public Commiepub() {
    }

    
    /** full constructor */
    public Commiepub(String branch, String publist, Date pubtime) {
        this.branch = branch;
        this.publist = publist;
        this.pubtime = pubtime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getPublist() {
        return this.publist;
    }
    
    public void setPublist(String publist) {
        this.publist = publist;
    }

    public Date getPubtime() {
        return this.pubtime;
    }
    
    public void setPubtime(Date pubtime) {
        this.pubtime = pubtime;
    }
   








}