package com.eaie.dbmanage;



/**
 * Course generated by MyEclipse - Hibernate Tools
 */

public class Course  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String coursename;
     private String coursememo;
     private String courseteacher;
     private String onlineurl;
     private String videolength;
     private String coursetime;


    // Constructors

    /** default constructor */
    public Course() {
    }

    
    /** full constructor */
    public Course(String coursename, String coursememo, String courseteacher, String onlineurl, String videolength, String coursetime) {
        this.coursename = coursename;
        this.coursememo = coursememo;
        this.courseteacher = courseteacher;
        this.onlineurl = onlineurl;
        this.videolength = videolength;
        this.coursetime = coursetime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    public String getCoursememo() {
        return this.coursememo;
    }
    
    public void setCoursememo(String coursememo) {
        this.coursememo = coursememo;
    }

    public String getCourseteacher() {
        return this.courseteacher;
    }
    
    public void setCourseteacher(String courseteacher) {
        this.courseteacher = courseteacher;
    }

    public String getOnlineurl() {
        return this.onlineurl;
    }
    
    public void setOnlineurl(String onlineurl) {
        this.onlineurl = onlineurl;
    }

    public String getVideolength() {
        return this.videolength;
    }
    
    public void setVideolength(String videolength) {
        this.videolength = videolength;
    }

    public String getCoursetime() {
        return this.coursetime;
    }
    
    public void setCoursetime(String coursetime) {
        this.coursetime = coursetime;
    }
   








}