package com.eaie.dbmanage;

import java.util.HashSet;
import java.util.Set;


/**
 * Expstudent generated by MyEclipse - Hibernate Tools
 */

public class Expstudent  implements java.io.Serializable {


    // Fields    

     private String stuid;
     private String name;
     private String pwd;
     private String classinfo;
     private String tel;
     private String email;
     private Set expchoses = new HashSet(0);


    // Constructors

    /** default constructor */
    public Expstudent() {
    }

	/** minimal constructor */
    public Expstudent(String stuid) {
        this.stuid = stuid;
    }
    
    /** full constructor */
    public Expstudent(String stuid, String name, String pwd, String classinfo, String tel, String email, Set expchoses) {
        this.stuid = stuid;
        this.name = name;
        this.pwd = pwd;
        this.classinfo = classinfo;
        this.tel = tel;
        this.email = email;
        this.expchoses = expchoses;
    }

   
    // Property accessors

    public String getStuid() {
        return this.stuid;
    }
    
    public void setStuid(String stuid) {
        this.stuid = stuid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getClassinfo() {
        return this.classinfo;
    }
    
    public void setClassinfo(String classinfo) {
        this.classinfo = classinfo;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set getExpchoses() {
        return this.expchoses;
    }
    
    public void setExpchoses(Set expchoses) {
        this.expchoses = expchoses;
    }
   








}