package com.eaie.dbmanage;

import java.util.HashSet;
import java.util.Set;


/**
 * Innovativelexp generated by MyEclipse - Hibernate Tools
 */

public class Innovativelexp  implements java.io.Serializable {


    // Fields    

     private Integer expid;
     private String name;
     private String teacher;
     private String student;
     private String contact;
     private String introduce;
     private String team;
     private String tutor;
     private String feature;
     private String intention;
     private String money;
     private Short ispass;
     private Set expchoses = new HashSet(0);


    // Constructors

    /** default constructor */
    public Innovativelexp() {
    }

    
    /** full constructor */
    public Innovativelexp(String name, String teacher, String student, String contact, String introduce, String team, String tutor, String feature, String intention, String money, Short ispass, Set expchoses) {
        this.name = name;
        this.teacher = teacher;
        this.student = student;
        this.contact = contact;
        this.introduce = introduce;
        this.team = team;
        this.tutor = tutor;
        this.feature = feature;
        this.intention = intention;
        this.money = money;
        this.ispass = ispass;
        this.expchoses = expchoses;
    }

   
    // Property accessors

    public Integer getExpid() {
        return this.expid;
    }
    
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getStudent() {
        return this.student;
    }
    
    public void setStudent(String student) {
        this.student = student;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getIntroduce() {
        return this.introduce;
    }
    
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }

    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }

    public String getFeature() {
        return this.feature;
    }
    
    public void setFeature(String feature) {
        this.feature = feature;
    }

    public String getIntention() {
        return this.intention;
    }
    
    public void setIntention(String intention) {
        this.intention = intention;
    }

    public String getMoney() {
        return this.money;
    }
    
    public void setMoney(String money) {
        this.money = money;
    }

    public Short getIspass() {
        return this.ispass;
    }
    
    public void setIspass(Short ispass) {
        this.ispass = ispass;
    }

    public Set getExpchoses() {
        return this.expchoses;
    }
    
    public void setExpchoses(Set expchoses) {
        this.expchoses = expchoses;
    }
   








}