package com.eaie.dbmanage;

import java.util.Date;

/**
 * Lecture generated by MyEclipse Persistence Tools
 */

public class Lecture implements java.io.Serializable {

	// Fields

	private Integer id;

	private String subject;

	private String lecturer;

	private String givetime;

	private String givesite;

	private String content;

	private Byte istop;

	private Byte isok;

	private String filename;

	private String fileurl;

	private String teacher;

	private Date pubtime;

	private Date endtime;

	private Integer hits;

	// Constructors

	/** default constructor */
	public Lecture() {
	}

	/** full constructor */
	public Lecture(String subject, String lecturer, String givetime,
			String givesite, String content, Byte istop, Byte isok,
			String filename, String fileurl, String teacher, Date pubtime,
			Date endtime, Integer hits) {
		this.subject = subject;
		this.lecturer = lecturer;
		this.givetime = givetime;
		this.givesite = givesite;
		this.content = content;
		this.istop = istop;
		this.isok = isok;
		this.filename = filename;
		this.fileurl = fileurl;
		this.teacher = teacher;
		this.pubtime = pubtime;
		this.endtime = endtime;
		this.hits = hits;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(String lecturer) {
		this.lecturer = lecturer;
	}

	public String getGivetime() {
		return this.givetime;
	}

	public void setGivetime(String givetime) {
		this.givetime = givetime;
	}

	public String getGivesite() {
		return this.givesite;
	}

	public void setGivesite(String givesite) {
		this.givesite = givesite;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Byte getIstop() {
		return this.istop;
	}

	public void setIstop(Byte istop) {
		this.istop = istop;
	}

	public Byte getIsok() {
		return this.isok;
	}

	public void setIsok(Byte isok) {
		this.isok = isok;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFileurl() {
		return this.fileurl;
	}

	public void setFileurl(String fileurl) {
		this.fileurl = fileurl;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public Date getPubtime() {
		return this.pubtime;
	}

	public void setPubtime(Date pubtime) {
		this.pubtime = pubtime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Integer getHits() {
		return this.hits;
	}

	public void setHits(Integer hits) {
		this.hits = hits;
	}

}