package com.eaie.dbmanage;

import java.util.Date;


/**
 * Message generated by MyEclipse - Hibernate Tools
 */

public class Message  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer bigclassid;
     private Byte isreply;
     private String part;
     private String title;
     private String content;
     private String name;
     private Date givetime;
     private String ip;
     private String reply;
     private String teacher;
     private Date replytime;


    // Constructors

    /** default constructor */
    public Message() {
    }

    
    /** full constructor */
    public Message(Integer bigclassid, Byte isreply, String part, String title, String content, String name, Date givetime, String ip, String reply, String teacher, Date replytime) {
        this.bigclassid = bigclassid;
        this.isreply = isreply;
        this.part = part;
        this.title = title;
        this.content = content;
        this.name = name;
        this.givetime = givetime;
        this.ip = ip;
        this.reply = reply;
        this.teacher = teacher;
        this.replytime = replytime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getBigclassid() {
        return this.bigclassid;
    }
    
    public void setBigclassid(Integer bigclassid) {
        this.bigclassid = bigclassid;
    }

    public Byte getIsreply() {
        return this.isreply;
    }
    
    public void setIsreply(Byte isreply) {
        this.isreply = isreply;
    }

    public String getPart() {
        return this.part;
    }
    
    public void setPart(String part) {
        this.part = part;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Date getGivetime() {
        return this.givetime;
    }
    
    public void setGivetime(Date givetime) {
        this.givetime = givetime;
    }

    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public Date getReplytime() {
        return this.replytime;
    }
    
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }
   








}