package com.eaie.dbmanage;



/**
 * Professor generated by MyEclipse - Hibernate Tools
 */

public class Professor  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer gradeid;
     private String name;
     private String pwd;
     private Byte sex;
     private String birth;
     private String degree;
     private String major;
     private String address;
     private String tel;
     private String email;
     private String imageurl;
     private String resume;
     private String field;
     private String book;
     private String projects;
     private String honor;
     private String orderid;


    // Constructors

    /** default constructor */
    public Professor() {
    }

    
    /** full constructor */
    public Professor(Integer gradeid, String name, String pwd, Byte sex, String birth, String degree, String major, String address, String tel, String email, String imageurl, String resume, String field, String book, String projects, String honor, String orderid) {
        this.gradeid = gradeid;
        this.name = name;
        this.pwd = pwd;
        this.sex = sex;
        this.birth = birth;
        this.degree = degree;
        this.major = major;
        this.address = address;
        this.tel = tel;
        this.email = email;
        this.imageurl = imageurl;
        this.resume = resume;
        this.field = field;
        this.book = book;
        this.projects = projects;
        this.honor = honor;
       
        this.orderid = orderid;
        
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGradeid() {
        return this.gradeid;
    }
    
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Byte getSex() {
        return this.sex;
    }
    
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public String getBirth() {
        return this.birth;
    }
    
    public void setBirth(String birth) {
        this.birth = birth;
    }

    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }

    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }

    public String getBook() {
        return this.book;
    }
    
    public void setBook(String book) {
        this.book = book;
    }

    public String getProjects() {
        return this.projects;
    }
    
    public void setProjects(String projects) {
        this.projects = projects;
    }

    public String getHonor() {
        return this.honor;
    }
    
    public void setHonor(String honor) {
        this.honor = honor;
    }

    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {

        this.orderid = orderid;
    }
   








}