package com.eaie.dbmanage;



/**
 * Smallclass generated by MyEclipse - Hibernate Tools
 */

public class Smallclass  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Bigclass bigclass;
     private String smallclass;
     private Integer smallclassid;
     private Integer bigclassid;


    // Constructors

    /** default constructor */
    public Smallclass() {
    }

    
    /** full constructor */
    public Smallclass(Bigclass bigclass, String smallclass, Integer smallclassid, Integer bigclassid) {
        this.bigclass = bigclass;
        this.smallclass = smallclass;
        this.smallclassid = smallclassid;
        this.bigclassid = bigclassid;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Bigclass getBigclass() {
        return this.bigclass;
    }
    
    public void setBigclass(Bigclass bigclass) {
        this.bigclass = bigclass;
    }

    public String getSmallclass() {
        return this.smallclass;
    }
    
    public void setSmallclass(String smallclass) {
        this.smallclass = smallclass;
    }

    public Integer getSmallclassid() {
        return this.smallclassid;
    }
    
    public void setSmallclassid(Integer smallclassid) {
        this.smallclassid = smallclassid;
    }

    public Integer getBigclassid() {
        return this.bigclassid;
    }
    
    public void setBigclassid(Integer bigclassid) {
        this.bigclassid = bigclassid;
    }
   








}