package com.eaie.dbmanage;



/**
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Student  implements java.io.Serializable {


    // Fields    

     private String stuid;
     private String name;
     private String sex;
     private String birth;
     private String nation;
     private String party;
     private String origin;
     private String perid;
     private String degree;
     private String major;
     private String banji;
     private String dorm;
     private String dormtel;
     private String mobiletel;
     private String pyfs;
     private String rxsj;
     private String xkml;
     private String gkzf;
     private String wyyz;
     private String address;
     private String hometel;
     private String postcode;
     private String father;
     private String fatherjob;
     private String mother;
     private String motherjob;
     private String techang;
     private String beizhu;
     private String isaid;
     private String aidlevel;
     private String aid1;
     private String aid2;
     private String aid3;
     private String aid4;
     private String homeinfo;
     private String isloan;
     private String aid;


    // Constructors

    /** default constructor */
    public Student() {
    }

	/** minimal constructor */
    public Student(String stuid) {
        this.stuid = stuid;
    }
    
    /** full constructor */
    public Student(String stuid, String name, String sex, String birth, String nation, String party, String origin, String perid, String degree, String major, String banji, String dorm, String dormtel, String mobiletel, String pyfs, String rxsj, String xkml, String gkzf, String wyyz, String address, String hometel, String postcode, String father, String fatherjob, String mother, String motherjob, String techang, String beizhu, String isaid, String aidlevel, String aid1, String aid2, String aid3, String aid4, String homeinfo, String isloan, String aid) {
        this.stuid = stuid;
        this.name = name;
        this.sex = sex;
        this.birth = birth;
        this.nation = nation;
        this.party = party;
        this.origin = origin;
        this.perid = perid;
        this.degree = degree;
        this.major = major;
        this.banji = banji;
        this.dorm = dorm;
        this.dormtel = dormtel;
        this.mobiletel = mobiletel;
        this.pyfs = pyfs;
        this.rxsj = rxsj;
        this.xkml = xkml;
        this.gkzf = gkzf;
        this.wyyz = wyyz;
        this.address = address;
        this.hometel = hometel;
        this.postcode = postcode;
        this.father = father;
        this.fatherjob = fatherjob;
        this.mother = mother;
        this.motherjob = motherjob;
        this.techang = techang;
        this.beizhu = beizhu;
        this.isaid = isaid;
        this.aidlevel = aidlevel;
        this.aid1 = aid1;
        this.aid2 = aid2;
        this.aid3 = aid3;
        this.aid4 = aid4;
        this.homeinfo = homeinfo;
        this.isloan = isloan;
        this.aid = aid;
    }

   
    // Property accessors

    public String getStuid() {
        return this.stuid;
    }
    
    public void setStuid(String stuid) {
        this.stuid = stuid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirth() {
        return this.birth;
    }
    
    public void setBirth(String birth) {
        this.birth = birth;
    }

    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getParty() {
        return this.party;
    }
    
    public void setParty(String party) {
        this.party = party;
    }

    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public String getPerid() {
        return this.perid;
    }
    
    public void setPerid(String perid) {
        this.perid = perid;
    }

    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }

    public String getBanji() {
        return this.banji;
    }
    
    public void setBanji(String banji) {
        this.banji = banji;
    }

    public String getDorm() {
        return this.dorm;
    }
    
    public void setDorm(String dorm) {
        this.dorm = dorm;
    }

    public String getDormtel() {
        return this.dormtel;
    }
    
    public void setDormtel(String dormtel) {
        this.dormtel = dormtel;
    }

    public String getMobiletel() {
        return this.mobiletel;
    }
    
    public void setMobiletel(String mobiletel) {
        this.mobiletel = mobiletel;
    }

    public String getPyfs() {
        return this.pyfs;
    }
    
    public void setPyfs(String pyfs) {
        this.pyfs = pyfs;
    }

    public String getRxsj() {
        return this.rxsj;
    }
    
    public void setRxsj(String rxsj) {
        this.rxsj = rxsj;
    }

    public String getXkml() {
        return this.xkml;
    }
    
    public void setXkml(String xkml) {
        this.xkml = xkml;
    }

    public String getGkzf() {
        return this.gkzf;
    }
    
    public void setGkzf(String gkzf) {
        this.gkzf = gkzf;
    }

    public String getWyyz() {
        return this.wyyz;
    }
    
    public void setWyyz(String wyyz) {
        this.wyyz = wyyz;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getHometel() {
        return this.hometel;
    }
    
    public void setHometel(String hometel) {
        this.hometel = hometel;
    }

    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getFather() {
        return this.father;
    }
    
    public void setFather(String father) {
        this.father = father;
    }

    public String getFatherjob() {
        return this.fatherjob;
    }
    
    public void setFatherjob(String fatherjob) {
        this.fatherjob = fatherjob;
    }

    public String getMother() {
        return this.mother;
    }
    
    public void setMother(String mother) {
        this.mother = mother;
    }

    public String getMotherjob() {
        return this.motherjob;
    }
    
    public void setMotherjob(String motherjob) {
        this.motherjob = motherjob;
    }

    public String getTechang() {
        return this.techang;
    }
    
    public void setTechang(String techang) {
        this.techang = techang;
    }

    public String getBeizhu() {
        return this.beizhu;
    }
    
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }

    public String getIsaid() {
        return this.isaid;
    }
    
    public void setIsaid(String isaid) {
        this.isaid = isaid;
    }

    public String getAidlevel() {
        return this.aidlevel;
    }
    
    public void setAidlevel(String aidlevel) {
        this.aidlevel = aidlevel;
    }

    public String getAid1() {
        return this.aid1;
    }
    
    public void setAid1(String aid1) {
        this.aid1 = aid1;
    }

    public String getAid2() {
        return this.aid2;
    }
    
    public void setAid2(String aid2) {
        this.aid2 = aid2;
    }

    public String getAid3() {
        return this.aid3;
    }
    
    public void setAid3(String aid3) {
        this.aid3 = aid3;
    }

    public String getAid4() {
        return this.aid4;
    }
    
    public void setAid4(String aid4) {
        this.aid4 = aid4;
    }

    public String getHomeinfo() {
        return this.homeinfo;
    }
    
    public void setHomeinfo(String homeinfo) {
        this.homeinfo = homeinfo;
    }

    public String getIsloan() {
        return this.isloan;
    }
    
    public void setIsloan(String isloan) {
        this.isloan = isloan;
    }

    public String getAid() {
        return this.aid;
    }
    
    public void setAid(String aid) {
        this.aid = aid;
    }
   








}