package com.eaie.dbmanage;

import java.util.Date;


/**
 * Teacher generated by MyEclipse - Hibernate Tools
 */

public class Teacher  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String teacher;
     private String pwd;
     private String part;
     private String bigclassid;
     private String lastloginip;
     private Date lastlogintime;
     private Integer logintimes;
     private Byte isadmin;


    // Constructors

    /** default constructor */
    public Teacher() {
    }

    
    /** full constructor */
    public Teacher(String teacher, String pwd, String part, String bigclassid, String lastloginip, Date lastlogintime, Integer logintimes, Byte isadmin) {
        this.teacher = teacher;
        this.pwd = pwd;
        this.part = part;
        this.bigclassid = bigclassid;
        this.lastloginip = lastloginip;
        this.lastlogintime = lastlogintime;
        this.logintimes = logintimes;
        this.isadmin = isadmin;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getPart() {
        return this.part;
    }
    
    public void setPart(String part) {
        this.part = part;
    }

    public String getBigclassid() {
        return this.bigclassid;
    }
    
    public void setBigclassid(String bigclassid) {
        this.bigclassid = bigclassid;
    }

    public String getLastloginip() {
        return this.lastloginip;
    }
    
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }

    public Date getLastlogintime() {
        return this.lastlogintime;
    }
    
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    public Integer getLogintimes() {
        return this.logintimes;
    }
    
    public void setLogintimes(Integer logintimes) {
        this.logintimes = logintimes;
    }

    public Byte getIsadmin() {
        return this.isadmin;
    }
    
    public void setIsadmin(Byte isadmin) {
        this.isadmin = isadmin;
    }
   








}