package com.eaie.dbmanage;

import java.util.Date;


/**
 * Vote generated by MyEclipse - Hibernate Tools
 */

public class Vote  implements java.io.Serializable {


    // Fields    

     private Integer subid;
     private Votepaper votepaper;
     private String subject;
     private String select1;
     private Integer answer1;
     private String select2;
     private Integer answer2;
     private String select3;
     private Integer answer3;
     private String select4;
     private Integer answer4;
     private String select5;
     private Integer answer5;
     private String select6;
     private Integer answer6;
     private String select7;
     private Integer answer7;
     private String select8;
     private Integer answer8;
     private Byte votetype;
     private String orderid;
     private String teacher;
     private Date pubtime;


    // Constructors

    /** default constructor */
    public Vote() {
    }

    
    /** full constructor */
    public Vote(Votepaper votepaper, String subject, String select1, Integer answer1, String select2, Integer answer2, String select3, Integer answer3, String select4, Integer answer4, String select5, Integer answer5, String select6, Integer answer6, String select7, Integer answer7, String select8, Integer answer8, Byte votetype, String orderid, String teacher, Date pubtime) {
        this.votepaper = votepaper;
        this.subject = subject;
        this.select1 = select1;
        this.answer1 = answer1;
        this.select2 = select2;
        this.answer2 = answer2;
        this.select3 = select3;
        this.answer3 = answer3;
        this.select4 = select4;
        this.answer4 = answer4;
        this.select5 = select5;
        this.answer5 = answer5;
        this.select6 = select6;
        this.answer6 = answer6;
        this.select7 = select7;
        this.answer7 = answer7;
        this.select8 = select8;
        this.answer8 = answer8;
        this.votetype = votetype;
        this.orderid = orderid;
        this.teacher = teacher;
        this.pubtime = pubtime;
    }

   
    // Property accessors

    public Integer getSubid() {
        return this.subid;
    }
    
    public void setSubid(Integer subid) {
        this.subid = subid;
    }

    public Votepaper getVotepaper() {
        return this.votepaper;
    }
    
    public void setVotepaper(Votepaper votepaper) {
        this.votepaper = votepaper;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getSelect1() {
        return this.select1;
    }
    
    public void setSelect1(String select1) {
        this.select1 = select1;
    }

    public Integer getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(Integer answer1) {
        this.answer1 = answer1;
    }

    public String getSelect2() {
        return this.select2;
    }
    
    public void setSelect2(String select2) {
        this.select2 = select2;
    }

    public Integer getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(Integer answer2) {
        this.answer2 = answer2;
    }

    public String getSelect3() {
        return this.select3;
    }
    
    public void setSelect3(String select3) {
        this.select3 = select3;
    }

    public Integer getAnswer3() {
        return this.answer3;
    }
    
    public void setAnswer3(Integer answer3) {
        this.answer3 = answer3;
    }

    public String getSelect4() {
        return this.select4;
    }
    
    public void setSelect4(String select4) {
        this.select4 = select4;
    }

    public Integer getAnswer4() {
        return this.answer4;
    }
    
    public void setAnswer4(Integer answer4) {
        this.answer4 = answer4;
    }

    public String getSelect5() {
        return this.select5;
    }
    
    public void setSelect5(String select5) {
        this.select5 = select5;
    }

    public Integer getAnswer5() {
        return this.answer5;
    }
    
    public void setAnswer5(Integer answer5) {
        this.answer5 = answer5;
    }

    public String getSelect6() {
        return this.select6;
    }
    
    public void setSelect6(String select6) {
        this.select6 = select6;
    }

    public Integer getAnswer6() {
        return this.answer6;
    }
    
    public void setAnswer6(Integer answer6) {
        this.answer6 = answer6;
    }

    public String getSelect7() {
        return this.select7;
    }
    
    public void setSelect7(String select7) {
        this.select7 = select7;
    }

    public Integer getAnswer7() {
        return this.answer7;
    }
    
    public void setAnswer7(Integer answer7) {
        this.answer7 = answer7;
    }

    public String getSelect8() {
        return this.select8;
    }
    
    public void setSelect8(String select8) {
        this.select8 = select8;
    }

    public Integer getAnswer8() {
        return this.answer8;
    }
    
    public void setAnswer8(Integer answer8) {
        this.answer8 = answer8;
    }

    public Byte getVotetype() {
        return this.votetype;
    }
    
    public void setVotetype(Byte votetype) {
        this.votetype = votetype;
    }

    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public Date getPubtime() {
        return this.pubtime;
    }
    
    public void setPubtime(Date pubtime) {
        this.pubtime = pubtime;
    }
   








}