package com.eaie.dbmanage;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Votepaper generated by MyEclipse - Hibernate Tools
 */

public class Votepaper  implements java.io.Serializable {


    // Fields    

     private Integer paperid;
     private String papername;
     private Byte isselected;
     private Date pubtime;
     private Set voteips = new HashSet(0);
     private Set votes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Votepaper() {
    }

    
    /** full constructor */
    public Votepaper(String papername, Byte isselected, Date pubtime, Set voteips, Set votes) {
        this.papername = papername;
        this.isselected = isselected;
        this.pubtime = pubtime;
        this.voteips = voteips;
        this.votes = votes;
    }

   
    // Property accessors

    public Integer getPaperid() {
        return this.paperid;
    }
    
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    public String getPapername() {
        return this.papername;
    }
    
    public void setPapername(String papername) {
        this.papername = papername;
    }

    public Byte getIsselected() {
        return this.isselected;
    }
    
    public void setIsselected(Byte isselected) {
        this.isselected = isselected;
    }

    public Date getPubtime() {
        return this.pubtime;
    }
    
    public void setPubtime(Date pubtime) {
        this.pubtime = pubtime;
    }

    public Set getVoteips() {
        return this.voteips;
    }
    
    public void setVoteips(Set voteips) {
        this.voteips = voteips;
    }

    public Set getVotes() {
        return this.votes;
    }
    
    public void setVotes(Set votes) {
        this.votes = votes;
    }
   








}