package com.eaie.dbmanage;

import java.util.Date;


/**
 * Voteip generated by MyEclipse - Hibernate Tools
 */

public class Voteip  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Votepaper votepaper;
     private String voteip;
     private Date votetime;


    // Constructors

    /** default constructor */
    public Voteip() {
    }

    
    /** full constructor */
    public Voteip(Votepaper votepaper, String voteip, Date votetime) {
        this.votepaper = votepaper;
        this.voteip = voteip;
        this.votetime = votetime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Votepaper getVotepaper() {
        return this.votepaper;
    }
    
    public void setVotepaper(Votepaper votepaper) {
        this.votepaper = votepaper;
    }

    public String getVoteip() {
        return this.voteip;
    }
    
    public void setVoteip(String voteip) {
        this.voteip = voteip;
    }

    public Date getVotetime() {
        return this.votetime;
    }
    
    public void setVotetime(Date votetime) {
        this.votetime = votetime;
    }
   








}