package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showleft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t<title>北京交通大学电子信息工程学院</title>\r\n");
      out.write("\t\t<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("\t\t<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// end hiding script -->\r\n");
      out.write("</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("<body topmargin=\"0\" rightmargin=\"0\" leftmargin=\"0\" rightmargin=\"0\">\r\n");
      out.write("\t\t");

			int type = Integer.parseInt(request.getParameter("type"));
			if (type != 0) {

				if (type == 1) {
		
      out.write("\r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top\r\n");
      out.write("\t\t\talign=left bgcolor=#f8f9fb width=210>\r\n");
      out.write("\t\t\t<tr height=8 width=242>\r\n");
      out.write("\t\t\t\t<td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\"\r\n");
      out.write("\t\t\t\t\theight=8></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=60>\r\n");
      out.write("\t\t\t\t<Td colspan=2 valign=\"top\"\r\n");
      out.write("\t\t\t\t\tbgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t</Td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t<a href=\"ShowContent.jsp?smallclassid=91&type=1\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;学院简介</a>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t<a href=\"ShowLeader.jsp?type=1\" class=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;学院领导</a>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t<a href=\"InstitutionList.jsp?type=1\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;机构设置</a>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

			} else if (type == 2) {
			
      out.write("\r\n");
      out.write("\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top align=left bgcolor=#f8f9fb width=220>\r\n");
      out.write("\t\t\t\t<tr height=8 width=242>\r\n");
      out.write("\t\t\t\t<td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\"\r\n");
      out.write("\t\t\t\t\theight=8></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=60>\r\n");
      out.write("\t\t\t\t<Td colspan=2 valign=\"top\"\r\n");
      out.write("\t\t\t\t\tbgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t</Td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=21&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;教学公告栏</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=25&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;办公流程</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=23&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;管理规定</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"downlist.jsp?bigclass=2&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;资料下载</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ShowContent.jsp?smallclassid=26&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;学院学科建设</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"UnderConstruction.jsp?type=2\" class=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;主讲介绍</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"course/CourseAll.jsp?type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;课程简介</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30\r\n");
      out.write("\t\t\t\t\t\tonClick=\"javascript:spread('list21','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;质量工程\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list21\" style=\"display:\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"quality/ExpList.jsp?type=2\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;大学生创新实验</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"message/MsgShow.jsp?id=2&type=2\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;学生留言</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://202.112.146.32:8081/BS/\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\">&nbsp;&nbsp;&nbsp;本科生论文选题系统</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

				} else if (type == 3) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top\r\n");
      out.write("\t\t\t\t\talign=left bgcolor=#f8f9fb width=220>\r\n");
      out.write("\t\t\t\t\t<tr height=8 width=242>\r\n");
      out.write("\t\t\t\t      <td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\" height=8></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr height=60>\r\n");
      out.write("\t\t\t\t     <Td colspan=2 valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t    <img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t      </Td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=31&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;研究生公告栏</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=32&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;研究生招生</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"tmszsxtstudentnew/tmlogin.jsp\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;推免生招生系统</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD></TR>\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.njtu.edu.cn/yanjiu/enrolment/index.asp\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;研究生招生系统</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=33&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;研究生培养</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/yanjiu/course/index.asp\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;研究生课程评价系统</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.njtu.edu.cn/lwtj/\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;研究生答辩论文提交</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.njtu.edu.cn/bslwtj/\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;博士生答辩论文提交</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/yanjiu/lwps/index.asp\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;研究生网上论文评审</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/yanjiu/assistant/index.asp\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;研究生三助系统</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=37&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;工程硕士</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"downlist.jsp?bigclass=3&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;常用资料</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"message/MsgShow.jsp?id=3&type=3\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;站内留言</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t<TD width=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?smallclassid=38&type=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;热点解答</a>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

					} else if (type == 4) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top\r\n");
      out.write("\t\t\t\t\t\talign=left bgcolor=#f8f9fb width=210>\r\n");
      out.write("\t\t\t\t       <tr height=8 width=242>\r\n");
      out.write("\t\t\t\t      <td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\" height=8></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr height=60>\r\n");
      out.write("\t\t\t\t     <Td colspan=2 valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t    <img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t      </Td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=41&type=4\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;科研公告</a>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"LectureList.jsp?type=4\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;学术活动</a>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"downlist.jsp?bigclass=4&type=4\" class=\"leftcolumn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;常用资料</a>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"http://www.njtu.edu.cn/jg/jgkj/paper/index.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;论文检索</a>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t");

						} else if (type == 5) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top\r\n");
      out.write("\t\t\t\t\t\t\talign=left bgcolor=#f8f9fb width=210>\r\n");
      out.write("\t\t\t\t\t\t\t<tr height=8 width=242>\r\n");
      out.write("\t\t\t\t      <td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\" height=8></td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr height=60>\r\n");
      out.write("\t\t\t\t     <Td colspan=2 valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t    <img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t      </Td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"teacher/teachers.jsp?gradeid=1&type=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;院士风采</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"teacher/teachers.jsp?gradeid=2&type=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;博导风采</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"teacher/teachers.jsp?gradeid=3&type=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;硕导风采</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"teacher/teachers.jsp?gradeid=4&type=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumn\" target=\"_parent\">&nbsp;&nbsp;&nbsp;其他教师</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD background=\"images/menu-.jpg\" width=170 height=30>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"teacher/login.jsp\" class=\"leftcolumn\" target=\"_blank\">&nbsp;&nbsp;&nbsp;--\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t教师登录 --</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							} else if (type == 6) {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top\r\n");
      out.write("\t\t\t\t\t\t\t\talign=left bgcolor=#f8f9fb width=200>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=8 width=242>\r\n");
      out.write("\t\t\t\t                <td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\" height=8></td>\r\n");
      out.write("\t\t\t                 </tr>\r\n");
      out.write("\t\t\t                <tr height=60>\r\n");
      out.write("\t\t\t\t              <Td colspan=2 valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t          <img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t                </Td>\r\n");
      out.write("\t\t\t                  </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD background=\"images/menu-l.jpg\" width=200 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list61','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;学科建设\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list61\" style=\"display:\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=58&type=6\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;国家级重点学科</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=59&type=6\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;部级重点学科</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=60&type=6\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;博士授权点</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=61&type=6\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;硕士授权点</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD background=\"images/menu-l.jpg\" width=200 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list62','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;实验室建设\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list62\" style=\"display:\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://iplab.bjtu.edu.cn/\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;下一代互联网研究中心</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"emcsite/index.asp\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;电磁兼容实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"jxjd/index.htm\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;国家电工电子教学基地</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-double.jpg\" width=170\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=35>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://ee.bjtu.edu.cn/dgjd/sfzx/index.htm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;国家电工电子实验教学<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;示范中心</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-double.jpg\" width=170\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=35>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=64\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;全光网络与现代通信网<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-double.jpg\" width=170\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=35>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=65\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;运输自动化与通信<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=66\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;光波技术工程研究中心</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://202.112.146.68:8082/web/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;通信与信息系统实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-double.jpg\" width=170\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=35>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/zdhsys/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;城市轨道交通<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;自动化与控制实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowContent.jsp?id=389\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;电子工程系实验室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD background=\"images/menu-l.jpg\" width=200 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list63','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;- 临时链接 -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list63\" style=\"display:\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"http://col.njtu.edu.cn/course/xnjp/dzxy/txxtyl/index.htm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;通信系统原理教学网站</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--.jpg\" width=170 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://col.njtu.edu.cn/jingpinke/08jpsb/mndzjs/index.html\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;模拟电子技术教学网站</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								} else if (type == 7) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top align=left bgcolor=#f8f9fb width=210>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=8 width=252>\r\n");
      out.write("\t\t\t\t     \t\t\t\t <td colspan=2 valign=\"bottom\" background=\"images/left-top.jpg\" height=8></td>\r\n");
      out.write("\t\t\t        \t\t\t\t</tr>\r\n");
      out.write("\t\t\t       \t\t\t\t <tr height=60>\r\n");
      out.write("\t\t\t\t    \t\t\t\t <Td colspan=2 valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t  <img src=\"images/corner_1.jpg\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t  </Td>\r\n");
      out.write("\t\t\t       \t\t\t\t </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=10></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD left-cellpadding=10 background=\"images/menu-l.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth=170 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list71','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;学生活动\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD width=40></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list71\" style=\"display:\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=81&type=7\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;活动报道</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"student/Apply.jsp?type=7\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;活动申请</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=82&type=7\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;学生作品</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=83&type=7\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;奥运专栏</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"vote/VoteList.jsp?type=7\" class=\"leftcolumns\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget=\"_parent\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;调查专区</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu-l.jpg\" width=170 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list72','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;学生组织\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD width=40></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list72\" style=\"display:\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/eaiesu/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;学生会</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/kexie/index.htm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;学生科协</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76-d.jpg\" width=220\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=35>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/study/items/index.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;三个代表重要思想<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;研究协会</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/volunteer/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;青年志愿者服务团</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/zuzhi/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;班级风采</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.njtu.edu.cn/ieee/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IEEE北京交大学生支会</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu-l.jpg\" width=170 height=30\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:spread('list73','img1');\" class=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;生活服务\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD width=40></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:220\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"220\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\" id=\"list73\" style=\"display:\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/eaiesu/st/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;同一趟车</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/eaiesu/jiaocai/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;书籍交流</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/eaiesu/kejian/index.asp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;课件下载</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<TR align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=10></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD background=\"images/menu--l-76.jpg\" width=220 height=20>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://eaie.bjtu.edu.cn/eaiesu/software/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"leftcolumns\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;常用软件</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD width=30></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									} else if (type == 10) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" valign=top align=left bgcolor=#f8f9fb width=210>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/b.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=61&type=10\" target=\"_parent\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/bzpxx.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/b-bottom.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ShowClass.jsp?id=62&type=10\" target=\"_parent\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/bjyzd.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/b-bottom.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"downlist.jsp?bigclass=6&type=10\" target=\"_parent\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/bcyzl.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/b-bottom.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://www.telehr.com/\" target=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/btxrcw.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/b-bottom.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
											}
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
